### ISSUE TITLE
There was an error fetching the list of voices. Make sure your API key is valid.

### ISSUE THREAD

**Issue by deepesch** [pgmichael/wavenet-for-chrome#35] opened 2020-12-16 09:53 UTC

**Comment by spencerpedro** [comment] 2021-02-27 15:52
I'm having the same issue; my API key is valid; it never gives me the chance to choose a language/voice. I'm on Windows 10.

**Comment by frank-zhangx** [comment] 2021-02-28 15:48
Same here, need some help!

**Comment by frank-zhangx** [comment] 2021-02-28 17:51
> I'm having the same issue; my API key is valid; it never gives me the chance to choose a language/voice. I'm on Windows 10.

I met the same problem today and tried two things and it is fixed now. I am not sure which one worked. I am no expert.

I have two google account and my default login account on chrome is account 1. But I used account 2 to sign in to the cloud platform. When I troubleshoot, it automatically logged into account 1, which had no credential to change any settings for account 2's projects. 
So the first thing I did was log in cloud platform with account 1.

The second thing probably is more relevant to this issue. While troubleshooting, chrome plugin suggested me go to the following site to check credentials where *****is numbers for my project I believe.
console.developers.google.com/apis/api/texttospeech.googleapis.com/overview?project=*************
At that site, I can't remember clearly but for the second step, it asked if I want to offer credential to one platform(couldn't remember the exact phrase) or two platforms. I chose 'both', and followed by creating some project email address. After finishing these steps, and waited for several mins, the problem is solved.

**Comment by spencerpedro** [comment] 2021-03-03 14:57
Thanks, that fixed it!

**Comment by BunyanPaul** [comment] 2022-01-06 22:24
This happened to me after my free trial to Google Cloud ended following the 90 days.

So, all services were stopped until I moved over to pay as you go.

**Comment by pgmichael** [comment] 2023-07-09 03:46
Closing this as it appears to be Google Cloud related. Thanks @frank-zhangx for providing a work around :)

**Closed by pgmichael** 2023-07-09 03:46 UTC
